# name: flutter_hangman
# description: Hangman Game

# version: 1.2.0+4005

# environment:
#   sdk: '>=3.0.0 <4.0.0'

# # dependencies:
# #   flutter:
# #     sdk: flutter
# #   cupertino_icons: ^0.1.2
# #   rflutter_alert: ^1.0.3
# #   material_design_icons_flutter: ^3.2.4495
# #   sqflite: ^1.3.0
# #   path: ^1.6.4
# #   flutter_spinkit: ^4.1.2
# #   date_format: ^2.0.7
# dependencies:
#   flutter:
#     sdk: flutter
#   cupertino_icons: ^0.1.2
#   rflutter_alert: ^1.0.3
#   material_design_icons_flutter: ^4.0.0-nullsafety.0
#   sqflite: ^2.0.0+3
#   path: ^1.8.0
#   flutter_spinkit: ^5.1.0
#   date_format: ^2.0.7

# dev_dependencies:
#   flutter_test:
#     sdk: flutter



# flutter:
#   uses-material-design: true
#   assets:
#     - images/
#     - res/
#   fonts:
#     - family: PatrickHand
#       fonts:
#         - asset: fonts/PatrickHand-Regular.ttf
#     - family: FiraMono
#       fonts:
#         - asset: fonts/FiraMono-Bold.ttf
#         - asset: fonts/FiraMono-Regular.ttf
name: flutter_hangman
description: Hangman Game

version: 1.2.0+4005

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  rflutter_alert: ^2.0.4
  material_design_icons_flutter: ^4.0.0-nullsafety.0
  sqflite: ^2.0.2+1
  path: ^1.8.0
  flutter_spinkit: ^5.1.0
  date_format: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
    - res/
  fonts:
    - family: PatrickHand
      fonts:
        - asset: fonts/PatrickHand-Regular.ttf
    - family: FiraMono
      fonts:
        - asset: fonts/FiraMono-Bold.ttf
        - asset: fonts/FiraMono-Regular.ttf
